apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
<<<<<<< HEAD
      - name: your-app
        image: arham1005/devops-assessment
        ports:
        - containerPort: 3000
=======
        - name: your-app
          image: arham1005/devops-assessment:main-0d548d99d32f49395f017361e43c71e879ed444f
          ports:
            - containerPort: 3000
>>>>>>> 20c976b8800ba63d4fcd5c2eee760de77b72d716
