apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynode-app
  namespace: nodejs
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynode-app
  template:
    metadata:
      labels:
        app: mynode-app
    spec:
      containers:
        - name: your-app-container
          image: arham1005/devops-assessment:main-6eb8d6264b887a5f2c06b410c10ba38c278eb14f
          ports:
            - containerPort: 8080
