apiVersion: v1  
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhcmhhbTEwMDUiLCJwYXNzd29yZCI6IldvaGxpZyIsImVtYWlsIjoiYXJoYW0uc2FuZ29pQHdvaGxpZy5jb20iLCJhdXRoIjoiWVhKb1lXMHhNREExT2xkdmFHeHBadz09In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2024-01-16T10:08:10Z"
  name: mycreds
  namespace: nodejs 
  resourceVersion: "72022"
  uid: f071e884-5b59-4bea-9599-524ca03b23bd
type: kubernetes.io/dockerconfigjson
