name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          IMAGE_TAG="darshan-48" # Custom tag name
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/devops-assessment:$IMAGE_TAG

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-assessment:darshan-48

      - name: CREATE DOCKER CONTAINER
        run: docker container run -d $IMAGE_TAG
     
